<a href="https://colab.research.google.com/github/senasung37/NLP/blob/main/KoBERT_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#기본모델

##라이브러리

In [ ]:
#transformers, torch 다운로드
!pip install transformers==3.5.1
!pip install torch==1.4.0

     |████████████████████████████████| 1.3 MB 7.1 MB/s 
     |████████████████████████████████| 2.9 MB 56.4 MB/s 
     |████████████████████████████████| 1.1 MB 33.3 MB/s 
     |████████████████████████████████| 895 kB 50.4 MB/s 
     |████████████████████████████████| 753.4 MB 6.8 kB/s 
  Attempting uninstall: torch
    Found existing installation: torch 1.10.0+cu111
    Uninstalling torch-1.10.0+cu111:
      Successfully uninstalled torch-1.10.0+cu111
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.11.1+cu111 requires torch==1.10.0, but you have torch 1.4.0 which is incompatible.
torchtext 0.11.0 requires torch==1.10.0, but you have torch 1.4.0 which is incompatible.
torchaudio 0.10.0+cu111 requires torch==1.10.0, but you have torch 1.4.0 which is incompatible.


In [ ]:
#라이브러리
from transformers import BertModel, BertTokenizer
import torch

##모델 다운로드 및 전처리

In [ ]:
#모델 다운로드
model = BertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
#문장 토크나이즈
sent = "I love Paris"
tokens = tokenizer.tokenize(sent)
tokens

['i', 'love', 'paris']

In [ ]:
#CLS, SEP 토큰 추가
tokens = ['[CLS]'] + tokens + ['[SEP]']
tokens

['[CLS]', 'i', 'love', 'paris', '[SEP]']

In [ ]:
#패딩 추가
tokens = tokens + ['[PAD]'] + ['[PAD]']
tokens


['[CLS]', 'i', 'love', 'paris', '[SEP]', '[PAD]', '[PAD]']

In [ ]:
#마스킹
mask = [1 if i != '[PAD]' else 0 for i in tokens]
mask

[1, 1, 1, 1, 1, 0, 0]

In [ ]:
#토큰 아이디로 변환
token_ids = tokenizer.convert_tokens_to_ids(tokens)
token_ids

[101, 1045, 2293, 3000, 102, 0, 0]

In [ ]:
#텐서로 변환
token_ids = torch.tensor(token_ids).unsqueeze(0)
mask = torch.tensor(mask).unsqueeze(0)

In [ ]:
token_ids

tensor([[ 101, 1045, 2293, 3000,  102,    0,    0]])

In [ ]:
mask

tensor([[1, 1, 1, 1, 1, 0, 0]])

##임베딩 추출

In [ ]:
#임베딩 추출
hidden_rep, cls_head = model(token_ids, attention_mask = mask)

In [ ]:
#은닉상태 표현 = 최종 인코더에서 얻은 모든 토큰의 표현 벡터들
hidden_rep

tensor([[[-0.0719,  0.2163,  0.0047,  ..., -0.5865,  0.2262,  0.1981],
         [ 0.2236,  0.6536, -0.2294,  ..., -0.3547,  0.5517, -0.2367],
         [ 1.0410,  0.7755,  1.0335,  ..., -0.5621,  0.5218, -0.0852],
         ...,
         [ 0.6156,  0.1036, -0.1875,  ..., -0.3799, -0.7008, -0.3500],
         [ 0.0791,  0.4287,  0.4147,  ..., -0.2417,  0.2403,  0.0378],
         [-0.0165,  0.2459,  0.4566,  ..., -0.2179,  0.1876,  0.0228]]],
       grad_fn=<NativeLayerNormBackward>)

In [ ]:
#[batch_size, sequence_length, hidden_size] -> hidden_size = 입력벡터의 길이
hidden_rep.shape

torch.Size([1, 7, 768])

In [ ]:
#두번째 토큰인 "i"의 표현벡터
hidden_rep[0][1]

tensor([ 2.2365e-01,  6.5363e-01, -2.2941e-01, -4.4871e-01, -9.5562e-02,
         2.1066e-01, -1.3226e-01,  1.4089e+00,  1.0668e-01, -2.9042e-02,
        -2.0937e-01, -5.2475e-01,  3.4771e-02,  2.7329e-01,  2.9269e-01,
         2.2714e-01,  4.7734e-01,  3.4942e-01,  1.2349e-01,  8.3038e-01,
         6.9122e-01,  2.3612e-01, -8.5010e-01, -2.0249e-02,  3.0893e-01,
        -2.4169e-01, -4.3335e-01,  1.5679e-01,  9.1365e-02, -3.6651e-01,
        -1.4479e-02, -9.2568e-02,  5.8239e-01,  7.3787e-01, -7.5602e-01,
        -1.9031e-01,  3.5895e-01, -2.0138e-01, -4.4486e-01,  1.4417e-01,
         8.1281e-02, -3.0344e-01, -1.2730e-01, -6.9157e-01,  2.7232e-01,
        -1.2914e+00,  2.2492e-01, -7.1515e-02,  7.0234e-01, -7.8603e-01,
        -8.6377e-02,  1.8485e-02,  5.6987e-02,  2.9224e-01, -1.8191e-01,
         1.1739e+00, -6.1941e-01, -3.6969e-01,  4.6749e-01,  5.2700e-01,
        -2.3670e-02, -1.0394e-01,  5.6715e-01, -6.3963e-01, -4.2078e-01,
         9.4930e-01, -4.8859e-01,  1.1718e-01,  1.6

In [ ]:
#CLS의 토큰표현
cls_head

tensor([[-9.0660e-01, -3.4189e-01, -3.3729e-01,  7.7140e-01,  6.0975e-02,
         -1.0525e-01,  9.0143e-01,  2.5822e-01, -2.7881e-01, -9.9997e-01,
         -1.0322e-01,  7.4772e-01,  9.8521e-01,  5.9799e-02,  9.4447e-01,
         -5.9859e-01, -2.0539e-01, -5.7386e-01,  3.7684e-01, -7.5183e-01,
          6.6604e-01,  9.9584e-01,  4.2231e-01,  2.2824e-01,  4.9139e-01,
          9.2378e-01, -6.6123e-01,  9.3111e-01,  9.6157e-01,  6.8816e-01,
         -6.7706e-01,  1.2696e-01, -9.8735e-01, -1.3884e-01, -4.2742e-01,
         -9.9151e-01,  3.1577e-01, -7.9245e-01,  1.1233e-01,  2.5441e-02,
         -9.0001e-01,  2.9572e-01,  9.9972e-01,  2.9506e-02,  9.4610e-02,
         -2.3375e-01, -1.0000e+00,  2.1042e-01, -8.8451e-01,  4.4717e-01,
          2.8363e-01,  2.3094e-01,  1.6396e-01,  4.6484e-01,  4.1578e-01,
          1.0880e-01, -6.9020e-02,  1.0251e-01, -1.8506e-01, -5.5142e-01,
         -5.4772e-01,  3.2660e-01, -4.7119e-01, -9.0760e-01,  4.0407e-01,
          8.4487e-03, -5.0541e-02, -2.

In [ ]:
#[batch_size, hidden_size]
cls_head.shape

torch.Size([1, 768])

##텍스트 감정분류 태스크

In [ ]:
!pip install nlp==0.4.0

     |████████████████████████████████| 1.7 MB 6.6 MB/s 
     |████████████████████████████████| 212 kB 38.5 MB/s 


In [ ]:
#라이브러리
from transformers import BertForSequenceClassification, BertTokenizerFast, Trainer, TrainingArguments
from nlp import load_dataset
import numpy as np

In [ ]:
#데이터셋 다운로드
!gdown https://drive.google.com/uc?id=11_M4ootuT7I1G0RlihcC0cA3Elqotlc-
dataset = load_dataset('csv', data_files='./imdbs.csv', split='train')

Downloading...
From: https://drive.google.com/uc?id=11_M4ootuT7I1G0RlihcC0cA3Elqotlc-
To: /content/imdbs.csv
100% 132k/132k [00:00<00:00, 59.8MB/s]


Using custom data configuration default


0 tables [00:00, ? tables/s]

Dataset csv downloaded and prepared to /root/.cache/huggingface/datasets/csv/default-11046c2826f07a01/0.0.0/ede98314803c971fef04bcee45d660c62f3332e8a74491e0b876106f3d99bd9b. Subsequent calls will reuse this data.


In [ ]:
dataset

Dataset(features: {'text': Value(dtype='string', id=None), 'label': Value(dtype='int64', id=None)}, num_rows: 100)

In [ ]:
type(dataset)

nlp.arrow_dataset.Dataset

In [ ]:
#데이터셋 분리
dataset = dataset.train_test_split(test_size=0.3)


  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
train = dataset['train']
test = dataset['test']

In [ ]:
#모델 다운로드(위보다 더 빠르고 편리한 버전)
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
#위 모델이 더 빠른 이유 -> 위에서 하던 전처리 step들을 한번에 해줌
tokenizer('I love Paris')

{'input_ids': [101, 1045, 2293, 3000, 102], 'token_type_ids': [0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1]}

In [ ]:
#패딩을 넣는 버전
tokenizer(['I love Paris', 'birds fly'], padding=True, max_length=5)

{'input_ids': [[101, 1045, 2293, 3000, 102], [101, 5055, 4875, 102, 0]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 0]]}

In [ ]:
#전처리 함수 만들기 
def preprocess(data):
  return tokenizer(data['text'], padding=True, truncation=True)

In [ ]:
#훈련, 테스트 데이터셋 전처리
train = train.map(preprocess, batched=True, batch_size=len(train))
test = train.map(preprocess, batched=True, batch_size=len(train))

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
#데이터셋에 필요한 열 및 형식
train.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])
test.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])

In [ ]:
train

Dataset(features: {'label': Value(dtype='int64', id=None), 'text': Value(dtype='string', id=None), 'input_ids': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'token_type_ids': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'attention_mask': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None)}, num_rows: 70)

In [ ]:
#모델 학습인수 설정
batch_size = 8
epochs = 2
warmup_steps = 500
weight_decay = 0.01

In [ ]:
#학습인수 정의
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=epochs,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    warmup_steps=warmup_steps,
    weight_decay=weight_decay,
    evaluate_during_training=True,
    logging_dir='./logs',
)

/usr/local/lib/python3.7/dist-packages/transformers/training_args.py:347: FutureWarning: The `evaluate_during_training` argument is deprecated in favor of `evaluation_strategy` (which has more options)
  FutureWarning,


In [ ]:
#트레이너 정의
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train,
    eval_dataset=test
)

In [ ]:
#학습 시작
trainer.train()

TrainOutput(global_step=18, training_loss=0.6772784656948514)

In [ ]:
#모델 평가
trainer.evaluate()

{'epoch': 2.0, 'eval_loss': 0.670756995677948}

#KoBERT

##라이브러리 설치 및 전처리

In [ ]:
#허깅페이스 지원되는 코버트 설치
!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'
!pip install torch==1.9.0 sentencepiece==0.1.96 transformers==4.8.1

  Cloning https://github.com/SKTBrain/KoBERT.git to /tmp/pip-install-ccmxc3q1/kobert-tokenizer_05470b9251fd424591dbb0e88c3b2b66
  Running command git clone -q https://github.com/SKTBrain/KoBERT.git /tmp/pip-install-ccmxc3q1/kobert-tokenizer_05470b9251fd424591dbb0e88c3b2b66
  Created wheel for kobert-tokenizer: filename=kobert_tokenizer-0.1-py3-none-any.whl size=4649 sha256=279b265c798af1c04b1bbd15909a02450457adad0fd6cd68ba7a9a034dcdb50f
  Stored in directory: /tmp/pip-ephem-wheel-cache-d1wox93v/wheels/10/b4/d9/cb627bbfaefa266657b0b4e8127f7bf96d27376fa1a23897b4
Successfully built kobert-tokenizer
     |████████████████████████████████| 831.4 MB 2.5 kB/s 
     |████████████████████████████████| 1.2 MB 8.9 MB/s 
     |████████████████████████████████| 2.5 MB 54.8 MB/s 
     |████████████████████████████████| 3.3 MB 50.5 MB/s 
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.9.3
    Uninstalling tokenizers-0.9.3:
      Successfully uninstalled tokenizers-0.9

In [ ]:
!pip install mxnet
!pip install gluonnlp pandas tqdm
!pip install sentencepiece
!pip install transformers
!pip install torch

     |████████████████████████████████| 47.3 MB 97 kB/s 
  Attempting uninstall: graphviz
    Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
     |████████████████████████████████| 344 kB 6.6 MB/s 
  Created wheel for gluonnlp: filename=gluonnlp-0.10.0-cp37-cp37m-linux_x86_64.whl size=595733 sha256=1e43ccd364d19c12785fef21963e83b5912d8570ce4d0e61fc57c3fb815d1ecc
  Stored in directory: /root/.cache/pip/wheels/be/b4/06/7f3fdfaf707e6b5e98b79c041e023acffbe395d78a527eae00
Successfully built gluonnlp


In [ ]:
#라이브러리 다운로드
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import gluonnlp as nlp
import numpy as np
from tqdm import tqdm, tqdm_notebook

# ★ Hugging Face를 통한 모델 및 토크나이저 Import
from kobert_tokenizer import KoBERTTokenizer
from transformers import BertModel

from transformers import AdamW
from transformers.optimization import get_cosine_schedule_with_warmup



In [ ]:
#모델 및 토크나이저 다운로드 + 예시
tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
bertmodel = BertModel.from_pretrained('skt/kobert-base-v1', return_dict=False)
vocab = nlp.vocab.BERTVocab.from_sentencepiece(tokenizer.vocab_file, padding_token='[PAD]')

Downloading:   0%|          | 0.00/371k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/244 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/432 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/535 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/369M [00:00<?, ?B/s]

In [ ]:
#한문장 정의 및 토큰화, 토큰 ID 얻기, 텐서로 변환
sent = "이번 대통령 선거는 박빙이었습니다"
tok_ids = tokenizer.encode(sent)
tok_ids = torch.tensor(tok_ids).unsqueeze(0)

In [ ]:
tok_ids

tensor([[   2, 3697, 1667, 2735, 5760, 2199, 6456, 7096, 6890,    3]])

##데이터 불러오기

In [ ]:
#네이버 영화리뷰 다운로드
!wget https://www.dropbox.com/s/374ftkec978br3d/ratings_train.txt?dl=1
!wget https://www.dropbox.com/s/977gbwh542gdy94/ratings_test.txt?dl=1

--2022-03-15 04:14:55--  https://www.dropbox.com/s/374ftkec978br3d/ratings_train.txt?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6030:18::a27d:5012
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/374ftkec978br3d/ratings_train.txt [following]
--2022-03-15 04:14:55--  https://www.dropbox.com/s/dl/374ftkec978br3d/ratings_train.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc943571c5a95a559d0b53768434.dl.dropboxusercontent.com/cd/0/get/BheaEnpX3WBNlXBRnmoac6zTzWiT5GQKCCkoOI7v_QplqeihxQmTUVIvb0OiJJlX9RBFjNpYoJ8FeDCaN9N8qLm40QB6p4s7dWHqBnYUxSH4UfN_kCvEPkM8h3OU3l7NpWOpmJmpDQXWxtixyXjFhnz7XUvRxqpEmgW7I8l02hT9nA/file?dl=1# [following]
--2022-03-15 04:14:56--  https://uc943571c5a95a559d0b53768434.dl.dropboxusercontent.com/cd/0/get/BheaEnpX3WBNlXBRnmoac6zTzWiT5GQKCCkoOI7v_QplqeihxQ

In [ ]:
#훈련, 테스트 데이터셋 나누기
#num_discard_samples (int, default 0) – Number of samples discarded at the head of the first file.
#field_indices (list of int or None, default None) – If set, for each sample, only fields with provided indices are selected as the output. Otherwise all fields are returned.
train = nlp.data.TSVDataset("ratings_train.txt?dl=1", field_indices=[1,2], num_discard_samples=1)
test = nlp.data.TSVDataset("ratings_test.txt?dl=1", field_indices=[1,2], num_discard_samples=1)

##모델링

In [ ]:
#데이터셋을 BERT 데이터로 변환
class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, vocab, max_len,
                 pad, pair):
        #nlp.data.BERTSentenceTransform - BERT style data transformation
        transform = nlp.data.BERTSentenceTransform(
            bert_tokenizer, max_seq_length=max_len, vocab=vocab, pad=pad, pair=pair)
        
        #문장 BERT 스타일 변환, 라벨 준비
        self.sentences = [transform([i[sent_idx]]) for i in dataset]
        self.labels = [np.int32(i[label_idx]) for i in dataset]

    #문장, 라벨 합치기
    def __getitem__(self, i):
        return (self.sentences[i] + (self.labels[i], ))

    def __len__(self):
        return (len(self.labels))

In [ ]:
#인수 설정
max_len = 64
batch_size = 64
warmup_ratio = 0.1
num_epochs = 5
max_grad_norm = 1
log_interval = 200
learning_rate =  5e-5

In [ ]:
#토크나이징
tok = tokenizer.tokenize

train_tok = BERTDataset(train, 0, 1, tok, vocab, max_len, True, False)
test_tok = BERTDataset(test, 0, 1, tok, vocab, max_len, True, False)

In [ ]:
train_tok

In [ ]:
train_dataloader = torch.utils.data.DataLoader(train_tok, batch_size=batch_size, num_workers=5)
test_dataloader = torch.utils.data.DataLoader(test_tok, batch_size=batch_size, num_workers=5)

In [ ]:
#버트 분류모델 정의
class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 num_classes=2,
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate
                 
        self.classifier = nn.Linear(hidden_size , num_classes)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)
    
    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)
        
        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device))
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

In [ ]:
# GPU 사용 시
device = torch.device("cuda:0")

In [ ]:
#버트 분류모델 정의
model = BERTClassifier(bertmodel,  dr_rate=0.5).to(device)

In [ ]:
# 옵티마이저, 스케줄 준비(linear warmup and decay)
no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]

In [ ]:
#옵티마이저, 손실 에폭, 웜업 설정
optimizer = AdamW(optimizer_grouped_parameters, lr=learning_rate)
loss_fn = nn.CrossEntropyLoss()

t_total = len(train_dataloader) * num_epochs
warmup_step = int(t_total * warmup_ratio)

scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_step, num_training_steps=t_total)

In [ ]:
#정확도 계산 함수
def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc

##학습

In [ ]:
#학습
for e in range(num_epochs):
    train_acc = 0.0
    test_acc = 0.0
    model.train()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(train_dataloader)):
        optimizer.zero_grad()
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        loss = loss_fn(out, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        optimizer.step()
        scheduler.step()  # Update learning rate schedule
        train_acc += calc_accuracy(out, label)
        if batch_id % log_interval == 0:
            print("epoch {} batch id {} loss {} train acc {}".format(e+1, batch_id+1, loss.data.cpu().numpy(), train_acc / (batch_id+1)))
    print("epoch {} train acc {}".format(e+1, train_acc / (batch_id+1)))
    model.eval()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(test_dataloader)):
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        test_acc += calc_accuracy(out, label)
    print("epoch {} test acc {}".format(e+1, test_acc / (batch_id+1)))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  


  0%|          | 0/2344 [00:00<?, ?it/s]

epoch 1 batch id 1 loss 0.7562511563301086 train acc 0.328125
epoch 1 batch id 201 loss 0.5007491111755371 train acc 0.5752487562189055


KeyboardInterrupt: ignored

#토이 프로젝트

##데이터 불러오기

In [ ]:
#허깅페이스 지원되는 코버트 설치
!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'
!pip install torch==1.9.0 sentencepiece==0.1.96 transformers==4.8.1

In [ ]:
!pip install mxnet
!pip install gluonnlp pandas tqdm
!pip install sentencepiece
!pip install transformers
!pip install torch

In [ ]:
#라이브러리 다운로드
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import gluonnlp as nlp
import numpy as np
from tqdm import tqdm, tqdm_notebook

# ★ Hugging Face를 통한 모델 및 토크나이저 Import
from kobert_tokenizer import KoBERTTokenizer
from transformers import BertModel

from transformers import AdamW
from transformers.optimization import get_cosine_schedule_with_warmup

In [ ]:
#csv파일 불러오기
from google.colab import files
uploaded = files.upload()

In [ ]:
#csv파일 df로 변환
import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['dev.hate.csv']))
df

In [ ]:
#라벨 종류 및 수 보기
df['label'].drop_duplicates(keep='last')

In [ ]:
#string to int 라벨링
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(df.label)
df['label'] = le.transform(df.label)
df

In [ ]:
#inverse(int to string) 라벨링
df['label'] = le.inverse_transform(df['label'])
df

In [ ]:
#null 값 확인
df.isna().sum()

In [ ]:
#데이터셋 분리
import numpy as np
from sklearn.model_selection import train_test_split
df_train, df_val = train_test_split(df, test_size=0.3, random_state=42)

In [ ]:
#1. csv파일 tsv로 변환
import csv
csv.writer(open('dev.hate.tsv', 'w+'), delimiter='\t').writerows(csv.reader(open("dev.hate.csv"))) 

In [ ]:
#2. df tsv로 변환
tsv_train = df_train.to_csv('train.tsv', sep="\t")
tsv_val = df_train.to_csv('val.tsv', sep="\t")

In [ ]:
#데이터 gluonnlp 데이터로 변환
train = nlp.data.TSVDataset("train.tsv", field_indices=[1,2], num_discard_samples=1)
val = nlp.data.TSVDataset("val.tsv", field_indices=[1,2], num_discard_samples=1)

##모델링

In [ ]:
#모델 및 토크나이저 다운로드
tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
bertmodel = BertModel.from_pretrained('skt/kobert-base-v1', return_dict=False)

#BERTVocab: changes default token representations of special tokens of gluonnlp.Vocab and adds parameters to specify mask, sep and cls tokens used by Bert models.
vocab = nlp.vocab.BERTVocab.from_sentencepiece(tokenizer.vocab_file, padding_token='[PAD]')

In [ ]:
#데이터셋을 BERT 데이터로 변환
class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, vocab, max_len,
                 pad, pair):
        #nlp.data.BERTSentenceTransform - BERT스타일로 데이터 변환
        transform = nlp.data.BERTSentenceTransform(
            bert_tokenizer, max_seq_length=max_len, vocab=vocab, pad=pad, pair=pair)
        
        #BERT 스타일 변환한 문장 + 라벨 준비
        self.sentences = [transform([i[sent_idx]]) for i in dataset]
        self.labels = [np.int32(i[label_idx]) for i in dataset]

    #Sample 만들기 
    def __getitem__(self, i):
        return (self.sentences[i] + (self.labels[i], ))

    def __len__(self):
        return (len(self.labels))

In [ ]:
#인수 설정
#warmup_ratio: learning rate를 0부터 5e-5까지 늘려가는 정도
#max_grad_norm: for gradient clipping -> mitigates exploding gradient problem
max_len = 64
batch_size = 64
warmup_ratio = 0.1
num_epochs = 10
max_grad_norm = 1
log_interval = 200
learning_rate =  5e-5

In [ ]:
#토크나이징
tok = tokenizer.tokenize
tok_train = BERTDataset(train, 0, 1, tok, vocab, max_len, True, False)
tok_val = BERTDataset(val, 0, 1, tok, vocab, max_len, True, False)

In [ ]:
train_dataloader = torch.utils.data.DataLoader(tok_train, batch_size=batch_size, num_workers=5)
val_dataloader = torch.utils.data.DataLoader(tok_val, batch_size=batch_size, num_workers=5)

In [ ]:
#버트 분류모델
class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 num_classes=3,
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate
        #Applies a linear transformation to the incoming data
        self.classifier = nn.Linear(hidden_size , num_classes)
        #drop out
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)

    #attention mask: 패딩은 0으로 변환, 실사용 토큰은 1로 변환
    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    #attention mask 정의 
    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)
        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device))
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

In [ ]:
#버트 분류모델 정의
model = BERTClassifier(bertmodel,  dr_rate=0.5)

In [ ]:
# 옵티마이저, 스케줄 준비(linear warmup and decay)
no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]

In [ ]:
#옵티마이저, 손실 에폭, 웜업 설정
optimizer = AdamW(optimizer_grouped_parameters, lr=learning_rate)
loss_fn = nn.CrossEntropyLoss()

t_total = len(train_dataloader) * num_epochs
warmup_step = int(t_total * warmup_ratio)

scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_step, num_training_steps=t_total)

In [ ]:
#정확도 계산 함수
def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc

In [ ]:
train_dataloader

In [ ]:
#학습
for e in range(num_epochs):
    train_acc = 0.0
    test_acc = 0.0
    #Sets the mode to train
    model.train()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(train_dataloader)):
        #Sets the gradients of all optimized torch.Tensor s to zero
        optimizer.zero_grad()
        token_ids = token_ids.long()
        segment_ids = segment_ids.long()
        valid_length = valid_length
        label = label.long()
        out = model(token_ids, valid_length, segment_ids)
        loss = loss_fn(out, label)
        loss.backward()
        #torch.nn.utils.clip_grad_norm_: gradient clipping -> mitigate exploding gradient problem
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        optimizer.step()
        scheduler.step()  # Update learning rate schedule
        train_acc += calc_accuracy(out, label)
        if batch_id % log_interval == 0:
            print("epoch {} batch id {} loss {} train acc {}".format(e+1, batch_id+1, loss.data.cpu().numpy(), train_acc / (batch_id+1)))
    print("epoch {} train acc {}".format(e+1, train_acc / (batch_id+1)))
    model.eval()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(test_dataloader)):
        token_ids = token_ids.long()
        segment_ids = segment_ids.long()
        valid_length= valid_length
        label = label.long()
        out = model(token_ids, valid_length, segment_ids)
        test_acc += calc_accuracy(out, label)
    print("epoch {} test acc {}".format(e+1, test_acc / (batch_id+1)))

In [ ]:
model.summary()

In [ ]:
from torchvision import models
from torchsummary import summary

In [ ]:
summary(model)